---
- name: EC2 gather facts.
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    profile: "{{ aws_default_profile }}"
    region: "{{ aws_default_region }}"
    filters:
      "tag:Name": "awstest"
  register: ec2_facts

- debug:
    msg: "Name: {{ item.id }}, ansible_ssh_host: {{ item.private_ip_address }}"
  with_items: "{{ ec2_facts.instances }}"

#- name: Start Instances
#  ec2:
#   aws_access_key: "{{ aws_access_key }}"
#    aws_secret_key: "{{ aws_secret_key }}"
#    instance_ids: "{{ item.id }}"
#    region: us-west-2
#    state: running
#  with_items: "{{ ec2_facts.instances }}"

- name: Stop instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_ids: "{{ item.id }}"
    region: "{{ aws_default_region }}"
    state: stopped
  with_items: "{{ ec2_facts.instances }}"
